# Generated by Django 3.2.13 on 2022-09-22 01:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_auto_20220922_1051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenitys',
            new_name='Amenity',
        ),
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
