# Generated by Django 4.1.1 on 2022-09-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_room_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="amenitys",
            new_name="amenities",
        ),
    ]
