# Generated by Django 4.1.1 on 2022-10-15 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0007_rename_amenitys_room_amenities"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="onwer",
            new_name="owner",
        ),
    ]
