# Generated by Django 4.1.1 on 2022-09-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perk",
            old_name="description",
            new_name="explanation",
        ),
        migrations.AlterField(
            model_name="perk",
            name="detail",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
