# Generated by Django 3.2.13 on 2022-09-16 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='제목')),
                ('is_private', models.BooleanField(default=True, verbose_name='비공개 여부')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='계약 담당자')),
            ],
            options={
                'verbose_name': '계약',
                'verbose_name_plural': '계약 목록',
                'db_table': 'contract',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('FINANCE_TEAM', 'FINANCE_TEAM'), ('SECURITY_TECH_TEAM', 'SECURITY_TECH_TEAM'), ('SECURITY_TEAM', 'SECURITY_TEAM'), ('LEGAL_TEAM', 'LEGAL_TEAM')], max_length=255, verbose_name='팀 소속')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='승인 여부')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contract', verbose_name='승인 여부')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='계약 담당자')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰 목록',
                'db_table': 'review',
            },
        ),
    ]
