# Generated by Django 3.2.13 on 2022-09-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='승인 여부'),
        ),
    ]
