# Generated by Django 3.2.12 on 2022-09-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20220911_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_reviewed',
            field=models.BooleanField(default=True),
        ),
    ]
