# Generated by Django 3.2.12 on 2022-09-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_contract_is_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='review_types',
            field=models.ManyToManyField(related_name='_contract_contract_review_types_+', to='contract.Review'),
        ),
    ]
