# Generated by Django 3.2.12 on 2022-09-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_contract_review_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='review_types',
            field=models.ManyToManyField(related_name='review_set', to='contract.Review'),
        ),
    ]
