# Generated by Django 3.2.12 on 2022-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_alter_contract_review_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='review_types',
        ),
        migrations.AddField(
            model_name='review',
            name='contract',
            field=models.ManyToManyField(to='contract.Contract'),
        ),
    ]
