# Generated by Django 3.2.12 on 2022-09-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_auto_20220911_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
