# Generated by Django 3.2.13 on 2022-09-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('재무팀', 'FINANCE_TEAM'), ('보안기술팀', 'SECURITY_TECH_TEAM'), ('보안팀', 'SECURITY_TEAM'), ('법무팀', 'LEGAL_TEAM'), ('팀없음', 'NO_TEAM')], max_length=50),
        ),
    ]
